<?php

$accounts = [
    'bringyourownideas',
    'dnadesign',
    'colymba',
    'silverstripe',
    'symbiote',
    'tractorcow'
];

$doNotMakeHookProtected = [
    'CMSEditLink', // Method on various DataObjects
    'MetaComponents', // Method on SiteTree
    'afterMemberLoggedIn', // Method on Member
    'afterMemberLoggedOut', // Method on Member
    'authenticationFailed', // called by AuditHook
    'beforeMemberLoggedIn', // called by RequestAuthenticationHandler
    'beforeMemberLoggedOut', // called by RequestAuthenticationHandler
    'can', // called by SiteTree, ChangeSet, CMSMain, others
    'canAccess', // called by EnvironmentCheck, others
    'canViewInLocale', // called by RecordLocale
    'canViewStage', // called by VersionedResolver
    'flushCache', // Called by many classes
    'getDefaultRecords', // Called by ErrorPage
    'init', // Called by LeftAndMain, Controller, many others
    'isArchived', // Method on Versioned
    'isAvailableInLocale', // Called by FluentFilteredExtension, FluentAdminTrait
    'onAfterBuild', // Called by DatabaseAdmin
    'populateDefaults', // Called by DataObject
    'registerFailedLogin', // Called by MemberAuthenticator, LoginHandler
    'requireDefaultRecords', // Called by various classes
    'updateEditForm', // called by AdvanedWorkflowExtension :/
    'updateFrontEndWorkflowActions', // called by advancedworkflow
    'updateFrontEndWorkflowFields', // called by advancedworkflow
    'updateLink', // called by VersionedTestSessionExtension
    'updateRelativeLink', // called by FluentSiteTreeExtension
    'updateURL', // called by DBFile, ImageTest, MailerSubscriber
    'updateWorkflowFields', // called by WorkflowInstance
    'validate', // Method on DataObject
    // manually moved from $makeProtected to this list
    'MetaTags', // method on SiteTree
    'forgotPassword', // method on LostPasswordHandler
];

$makeHookProtected = [
    'afterCallActionHandler',
    'afterCallActionURLHandler',
    'afterCallFormHandler',
    'afterFindOrCreateAdmin',
    'afterFindOrCreateDefaultAdmin',
    'afterGetAllLivePageURLs',
    'afterInsertBaseRows',
    'afterInsertTypeSpecificRows',
    'afterLogin',
    'afterLogout',
    'afterMigrateHasManyRelations',
    'afterMigrateManyManyRelations',
    'afterMigrateTitleColumn',
    'afterPerformMigration',
    'afterPerformReadonlyTransformation',
    'afterSetOwnerForHasOneLinks',
    'afterUpdateFormField',
    'afterUpdateSiteTreeRows',
    'alternateGetByLink',
    'alternateSiteConfig',
    'augmentAllChildrenIncludingDeleted',
    'augmentDataQueryCreation',
    'augmentDatabase',
    'augmentHydrateFields',
    'augmentLoadLazyFields',
    'augmentSQL',
    'augmentStageChildren',
    'augmentSyncLinkTracking',
    'augmentValidURLSegment',
    'augmentWrite',
    'augmentWriteDeletedVersion',
    'authenticationFailedUnknownUser',
    'authenticationSucceeded',
    'beforeCallActionHandler',
    'beforeCallActionURLHandler',
    'beforeCallFormHandler',
    'beforeFindOrCreateAdmin',
    'beforeFindOrCreateDefaultAdmin',
    'beforeGetAllLivePageURLs',
    'beforeInsertBaseRows',
    'beforeInsertTypeSpecificRows',
    'beforeLogin',
    'beforeLogout',
    'beforeMigrateHasManyRelations',
    'beforeMigrateManyManyRelations',
    'beforeMigrateTitleColumn',
    'beforePerformMigration',
    'beforeSetOwnerForHasOneLinks',
    'beforeUpdateFormField',
    'beforeUpdateSiteTreeRows',
    'cacheKeyComponent',
    'canLogIn',
    'contentcontrollerInit',
    'extendCanExecute',
    'failedLogin',
    'failedLogout',
    'getErrorRecordFor',
    'handleAccountReset',
    'memberAutoLoggedIn',
    'migrateHasOneForLinkSubclass',
    'modelascontrollerInit',
    'onActionComplete',
    'onActionStart',
    'onAfterApplyState',
    'onAfterArchive',
    'onAfterChangePassword',
    'onAfterClear',
    'onAfterCopyLocale',
    'onAfterDuplicate',
    'onAfterDuplicateToSubsite',
    'onAfterEndTestSession',
    'onAfterFormSaveInto',
    'onAfterGeneratePageResponse',
    'onAfterGenerateToken',
    'onAfterInit',
    'onAfterLDAPGroupSyncTask',
    'onAfterLDAPMemberSyncTask',
    'onAfterLoad',
    'onAfterLoadIntoFile',
    'onAfterLocalisedCopy',
    'onAfterLocalisedCopyRelation',
    'onAfterParse',
    'onAfterProcessAll',
    'onAfterProcessRecord',
    'onAfterPublish',
    'onAfterPublishRecursive',
    'onAfterRenewToken',
    'onAfterReorderItems',
    'onAfterRequireDefaultElementalRecords',
    'onAfterRestoreToStage',
    'onAfterRevertToLive',
    'onAfterRollbackRecursive',
    'onAfterRollbackSingle',
    'onAfterSave',
    'onAfterSend',
    'onAfterSetPassword',
    'onAfterSkippedWrite',
    'onAfterStartTestSession',
    'onAfterUnpublish',
    'onAfterUpdateTestSession',
    'onAfterUpload',
    'onAfterVersionDelete',
    'onAfterVersionedPublish',
    'onAfterWorkflowPublish',
    'onAfterWorkflowUnublish',
    'onAfterWriteToStage',
    'onBeforeApplyState',
    'onBeforeArchive',
    'onBeforeBuild',
    'onBeforeChangePassword',
    'onBeforeClear',
    'onBeforeCopyLocale',
    'onBeforeDuplicate',
    'onBeforeDuplicateToSubsite',
    'onBeforeEndTestSession',
    'onBeforeFormSaveInto',
    'onBeforeGeneratePageResponse',
    'onBeforeHTTPError',
    'onBeforeHTTPError{$errorCode}',
    'onBeforeInit',
    'onBeforeJSONError',
    'onBeforeJSONError{$errorCode}',
    'onBeforeLocalisedCopy',
    'onBeforeLocalisedCopyRelation',
    'onBeforeManipulate',
    'onBeforeParse',
    'onBeforeProcessAll',
    'onBeforePublish',
    'onBeforePublishRecursive',
    'onBeforeRemoveLoginSession',
    'onBeforeRender',
    'onBeforeRenderHolder',
    'onBeforeReorderItems',
    'onBeforeRequireDefaultElementalRecords',
    'onBeforeRestoreToStage',
    'onBeforeRevertToLive',
    'onBeforeRollback',
    'onBeforeRollbackRecursive',
    'onBeforeRollbackSingle',
    'onBeforeSaveRequestToStore',
    'onBeforeSecurityLogin',
    'onBeforeSend',
    'onBeforeSetPassword',
    'onBeforeStartTestSession',
    'onBeforeUnpublish',
    'onBeforeUpdateTestSession',
    'onBeforeVersionedPublish',
    'onBeforeWriteToStage',
    'onBulkUpload',
    'onMethodVerificationFailure',
    'onMethodVerificationSuccess',
    'onPopulationFromField',
    'onPrepopulateTreeDataCache',
    'onRealMeLoginFailure',
    'onRealMeLoginSuccess',
    'onRegisterMethod',
    'onRegisterMethodFailure',
    'onSkipRegistration',
    'onTransition',
    'permissionDenied',
    'processHTML',
    'updateAbsoluteLink',
    'updateAfterProcess',
    'updateAlerts',
    'updateAllowedChildren',
    'updateAnchorAndQueryString',
    'updateAnchorsInContent',
    'updateAnchorsOnPage',
    'updateApplyVersionedFiltersAsConditions',
    'updateAttributes',
    'updateAvailableTypesForClass',
    'updateBadge',
    'updateBadgeLabel',
    'updateBadges',
    'updateBaseFields',
    'updateBatchActionsForm',
    'updateBlockSchema',
    'updateBreadcrumbs',
    'updateCMSActions',
    'updateCMSCompositeValidator',
    'updateCMSEditLink',
    'updateCMSTreeTitle',
    'updateCanAttachFileForRecipient',
    'updateCandidateAuthors',
    'updateCandidateUsers',
    'updateChangeSetResource',
    'updateChangeType',
    'updateChangedPasswordEmail',
    'updateCharacterSet',
    'updateCheckForBrokenLinks',
    'updateChildFilter',
    'updateClientConfig',
    'updateClientOptions',
    'updateColumns',
    'updateConfig',
    'updateContentForCmsSearch',
    'updateContentForSearchIndex',
    'updateCurrentPageID',
    'updateCurrentSiteConfig',
    'updateDataSchema',
    'updateDateFormat',
    'updateDefaultFrom',
    'updateDefaultLinkTitle',
    'updateDeleteTable',
    'updateDeleteTables',
    'updateDisownershipQuery',
    'updateDoAdd',
    'updateDropdownFilterOptions',
    'updateEditFormAfter',
    'updateEditLinkForDataObject',
    'updateEmail',
    'updateEmailData',
    'updateErrorFilename',
    'updateExcludedURLSegments',
    'updateExportButton',
    'updateExtraTreeTools',
    'updateFieldLabels',
    'updateFieldValidationOptions',
    'updateFilesInUse',
    'updateFilterDescription',
    'updateFilteredEmailRecipients',
    'updateFluentDirectorDefaultLocale',
    'updateFluentLocales',
    'updateFluentRoutes',
    'updateFluentRoutesForLocale',
    'updateForTemplateDefaultStyles',
    'updateForTemplateTemplate',
    'updateForgotPasswordEmail',
    'updateForm',
    'updateFormActions',
    'updateFormFields',
    'updateFormOptions',
    'updateFormScaffolder',
    'updateFormValidator',
    'updateFormatUrl',
    'updateFrontEndRequiredFields',
    'updateFrontendFormRequirements',
    'updateGeneratedThumbnails',
    'updateGetArchive',
    'updateGetBlogPosts',
    'updateGetData',
    'updateGetOptions',
    'updateGetTypes',
    'updateGetURL',
    'updateGetURLBeforeAnchor',
    'updateGetUrls',
    'updateGetVersionNumberByStage',
    'updateGrant',
    'updateGridField',
    'updateGridFieldConfig',
    'updateGroups',
    'updateGroupsFilter',
    'updateHintsCacheKey',
    'updateHomepageLink',
    'updateHydratedJob',
    'updateImportForm',
    'updateInheritableQueryParams',
    'updateIsArchived',
    'updateIsContributor',
    'updateIsEditor',
    'updateIsMigratable',
    'updateIsOnDraft',
    'updateIsPublished',
    'updateIsSiteUrl',
    'updateIsWriter',
    'updateItemEditForm',
    'updateItemRequestClass',
    'updateItemRequestHandler',
    'updateJobDescriptorAndJobOnCompletion',
    'updateJobDescriptorAndJobOnException',
    'updateJobDescriptorBeforeQueued',
    'updateJobDescriptorOnInitialisationException',
    'updateJoinTableName',
    'updateLinkPageAdd',
    'updateLinkWithSearch',
    'updateList',
    'updateListView',
    'updateLocalePageController',
    'updateLocalisationTabColumns',
    'updateLocalisationTabConfig',
    'updateLocaliseSelect',
    'updateLocaliseSelectDefault',
    'updateLoginAttempt',
    'updateManyManyComponents',
    'updateMemberFormFields',
    'updateMemberPasswordField',
    'updateMetaTitle',
    'updateMigratedElement',
    'updateName',
    'updateNeedsMigration',
    'updateNestedGroupsFilter',
    'updateNewLink',
    'updateNewRowClasses',
    'updateNodesFilter',
    'updateNotifyUsersCMSFields',
    'updateOnMessage',
    'updatePHP',
    'updatePackageInfo',
    'updatePage',
    'updatePageFilter',
    'updatePageOptions',
    'updatePageShouldSkip',
    'updateParameterFields',
    'updatePlaceholderGroups',
    'updatePopoverActions',
    'updatePostURL',
    'updatePrePopulateVersionNumberCache',
    'updatePreviewEnabled',
    'updatePreviewLink',
    'updatePrintData',
    'updatePrintExportColumns',
    'updateProgressForm',
    'updateRandomPassword',
    'updateReceivedFormSubmissionData',
    'updateRecordLocaleStagesDiffer',
    'updateRedirectionLink',
    'updateRenderTemplates',
    'updateRequestURL',
    'updateRequiredFields',
    'updateResetAccountForm',
    'updateResponse',
    'updateRestfulGetHandler',
    'updateRowAttributes',
    'updateRss',
    'updateRules',
    'updateSchema',
    'updateSchemaValidation',
    'updateSearchContext',
    'updateSearchForm',
    'updateSearchableFields',
    'updateSettingsFields',
    'updateShareTokenLink',
    'updateShouldDropColumn',
    'updateShouldMigrateColumn',
    'updateShouldPublishLink',
    'updateShouldPublishLinks',
    'updateSiteTreeAsUL',
    'updateSiteTreeExcludedClassNames',
    'updateSiteTreeHints',
    'updateSourceParams',
    'updateSourceRecords',
    'updateStagesDiffer',
    'updateStartForm',
    'updateStatusFlags',
    'updateStyleVariant',
    'updateSubmissionsGridField',
    'updateSummary',
    'updateSummaryFields',
    'updateTimeFormat',
    'updateTotp',
    'updateTrackedFormUpload',
    'updateTreeTitle',
    'updateURLSegment',
    'updateUsage',
    'updateUsageAncestorDataObjects',
    'updateUsageDataObject',
    'updateUsageExcludedClasses',
    'updateUsersFilter',
    'updateUsersWithIteratorFilter',
    'updateValidTransitions',
    'updateValidatePassword',
    'updateValidationResult',
    'updateValidator',
    'updateVersionModules',
    'updateView',
    'updateWorkflowEditForm',
    'updatelocaliseCondition',
    'updatelocaliseConditionDefault',
    // manually moved from $doNotMakeHookProtected to this list
    'augmentNewSiteTreeItem', // call was example in code comment
    'accessedCMS', // call was example in code comment
    'updateCMSFields', // call was example in code comment
    'updateFrontEndFields', // call was example in code comment
    // Only called within it's own class so can be protected
    'onAfterDelete', // Called by DataObject
    'onAfterWrite', // Called by DataObject
    'onBeforeDelete', // Called by DataObject
    'onBeforeWrite', // Called by DataObject, elemental Resolver (have updated BaseElement.php)
];